server:
  port: 8888
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabianoalbuquerque/ms-config-server
          default-label: main
          search-paths:
            - 'greeting-service*'
